version: "3.8"

services:

  nginx:
    image: nginx:1.19.0-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx_logs:/var/log/nginx
      - ./nginx:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - msk_app

  msk_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: msk_app
    restart: unless-stopped
    expose:
      - 8080
    depends_on:
      - front
      - db

  front:
    build:
      context: .
      dockerfile: Dockerfile2
    container_name: front
    restart: unless-stopped
    expose:
      - 8082

  db:
    image: postgis/postgis
    container_name: db
    restart: unless-stopped
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=qwerty12345
      - POSTGRES_DB=db
    ports:
      - "5432:5432"

