version: "3.8"

services:

  nginx:
    image: nginx:1.19.0-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
#      - ./index.html:/var/www/html/index.html
      - ./nginx_logs:/var/log/nginx
      - ./nginx:/etc/nginx/conf.d/nginx.conf
#      - /etc/ssl/private/bundle.crt:/etc/ssl/bundle.crt
#      - /etc/ssl/private/private.key:/etc/ssl/www.dora.team.key
    depends_on:
      - msk_app

  msk_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: msk_app
    restart: unless-stopped
    expose:
      - 8080
    depends_on:
      - front
      - redis

  front:
    build:
      context: .
      dockerfile: Dockerfile2
    container_name: front
    restart: unless-stopped
    expose:
      - 8082

  redis:
    image: redis:6.2.6-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379
