version: "3.8"

services:

  msk_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: msk_app
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - 8080
    depends_on:
      - front
      - db
    networks:
      - project1

  front:
    build:
      context: .
      dockerfile: Dockerfile2
    container_name: front
    restart: unless-stopped
    expose:
      - 8082
    networks:
      - project1

  db:
    image: postgis/postgis
    container_name: db
    restart: unless-stopped
    volumes:
      - ./db_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - project1

# Подразумевается раздельное использование контейнера с reverse proxy и с проектом
networks:
  project1:
